version: '3'
services:
  server1:
    image: server1
    container_name: server1
    build:
      context: ./server1
    networks:
      - examplenet

  server2:
    image: server2
    container_name: server2
    build:
      context: ./server2
    networks:
      - examplenet

  proxy:
    image: nginx:alpine
    container_name: proxy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - examplenet

networks:
  examplenet:
